# Generated by ChatGPT
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("distance_unit", models.CharField(choices=[("km", "Kilometres"), ("mi", "Miles")], default="km", max_length=2)),
                ("volume_unit", models.CharField(choices=[("L", "Litres"), ("gal", "Gallons")], default="L", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=255)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
